#!/bin/sh
### BEGIN INIT INFO
# Provides:          stand for test modules
# Default-Start:     5
# Default-Stop:      0 1 2 3 6
# Short-Description: stand for test modules
### END INIT INFO

DAEMON_PATH=/usr/bin/stand
DAEMON_NAME=`basename $DAEMON_PATH`
CONF_NAME=/stand.json

. /etc/init.d/functions

test -x $DAEMON_PATH || exit 0

PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

RETVAL=0

case "$1" in
    start)
        echo -n "Starting $DAEMON_NAME: "
	CONF_PATH="/run/media/mmcblk1p1"$CONF_NAME
	if [ ! -f $CONF_PATH ] 
	then
	  CONF_PATH="/run/media/mmcblk0p1"$CONF_NAME	
	fi
    if [ ! -f $CONF_PATH ] 
    then
      CONF_PATH="/run/media/sda1"$CONF_NAME    
    fi
    if [ ! -f $CONF_PATH ] 
    then
      CONF_PATH="/run/media/sdb1"$CONF_NAME    
    fi
    if [ ! -f $CONF_PATH ] 
    then
        echo Not found config - $CONF_PATH
        echo Stand not started
        sh /etc/stand/test/show_message.sh "Error: not found config "$CONF_NAME
        exit 1
    fi

  
	echo Found config - $CONF_PATH
        su -l -c "$DAEMON_PATH --conf=$CONF_PATH &"
        sleep 1
	killall migrate
        sh /etc/stand/test/show_message.sh "Started test with conf "$CONF_PATH
#/run/media/mmcblk1p1/srvDVR/srvDVR.ini &"
        RETVAL=$?
        if [ $RETVAL -eq 0 ] ; then
            echo "OK"
            touch /var/lock/subsys/$DAEMON_NAME
        else
            echo "FAIL"
        fi
        ;;

    stop)
        echo -n "Stopping $DAEMON_NAME: "
        count=0
        while [ -n "`/bin/pidof $DAEMON_PATH`" -a $count -lt 10 ] ; do
            killproc $DAEMON_PATH >& /dev/null
            sleep 1
            RETVAL=$?
            if [ $RETVAL != 0 -o -n "`/bin/pidof $DAEMON_PATH`" ] ; then
                sleep 1
            fi
            count=`expr $count + 1`
        done
        rm -f /var/lock/subsys/$DAEMON_NAME
        if [ -n "`/bin/pidof $DAEMON_PATH`" ] ; then
            echo "FAIL"
        else
            echo "OK"
        fi
        ;;

    restart)
        $0 stop
        sleep 1
        $0 start
        ;;

    status)
        status $DAEMON_NAME
        RETVAL=$?
        ;;

    condrestart)
        [ -f /var/lock/subsys/$DAEMON_NAME ] && $0 restart
        ;;

    *)
        echo "usage: $0 { start | stop | status | restart | condrestart | status }"
        ;;
esac

exit $RETVAL
